### PR TITLE
Metadata config pages

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning can this branch be refreshed with latest please?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It should be current now. Tests are failing I believe because it depends on a PR in jekyll-open-sdg-plugins.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry, this _is_ jekyll-open-sdg-plugins, I understand now... One sec...

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok, it should be current now.

**Pull request merged**
